name: Sync
on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "*/10 * * * *"

jobs:
  sync:
    name: Sync With Upstream
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_PUBLIC_GITHUB_TOKEN }}
      - run: |
          git config --global user.name "depot-bot"
          git config --global user.email "71396760+depot-bot@users.noreply.github.com"
          git submodule init
          git submodule update --remote --merge
          git commit -m "Update submodule from upstream: $(date)" || echo "No changes"
          git push origin main
        env:
          BOT_PUBLIC_GITHUB_TOKEN: ${{ secrets.BOT_PUBLIC_GITHUB_TOKEN }}
